# Работа с датасетами

## Библиотеки

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

## Параметры

Корневая папка со всеми датасетами

In [2]:
root_dir = Path(r"./datasets")

Закрывающийся магазин. Указать id в виде строки

In [3]:
closing_store = "10"

Считать ли алкогольные товары отдельно. Это нужно, так как не у всех организаций есть лицензия на продажу алкоголя. В таком случае, нужно искать наилучшее распределение среди магазинов, которые состоят в той же организации, что и закрывающийся

In [4]:
separate_alcohol = False

Минимальный срок хранения распределяемого товара. Это обусловлено тем, что процесс закрытия магазина не быстрый, обычно занимает не меньше месяца времени, потому скоропортящиеся товары в любом случае не успеют быть распределены.

Значение переменной 0 означает, что срок годности любой

In [5]:
spoilage_threshold = 30

Не все товары измеряются поштучно, некоторые измеряются по весу, другие - по длине. В таком случае, нужно определить, сколько килограмм или метров содержит условно одна штука товара

In [6]:
kilos_in_one_piece = 1.0
meters_in_one_piece = 1.0

Стоит ли искать магазины с тем же куратором или организацией, что и закрывающийся магазин. Это нужно, так как контакты между разными организациями или кураторами добавляют лишние издержки, проще когда всё происходит в рамках одной компании или куратора.

In [7]:
same_curator = False
same_organization = False

## Подгрузка датасетов

In [8]:
assortment = pd.read_csv(root_dir / "Ассортимент" / "Assortment.csv", sep=";", dtype={"№Магазина" : "str"})  # т.к. под номером может быть РЦ
assortment.head()

,№Магазина,Номер SKU,Ассортимент Статус,Ассортимент Вид,КоличествоКонечныйОстатокНП
0,54,108283,Введен,Регулярный,"-0,510"
1,54,223588,Введен,Регулярный,"-1,422"
2,54,92602,Введен,Регулярный,"-1,504"
3,54,188801,Введен,Регулярный,"3,304"
4,54,169467,Введен,Регулярный,"-6,256"

In [9]:
leftovers = pd.read_csv(root_dir / "Остатки" / "Stocks.csv", sep=";", dtype={"номер магазина" : "str"})
leftovers.head()

  номер магазина  код товара остаток остаток_робот
0             05      215673   4,000         4,000
1             75      215673   8,000         8,000
2            137      226249  24,000        24,000
3             39      226249  29,000        29,000
4             08      226249  30,000        30,000

In [10]:
facings = pd.read_csv(root_dir / "Планограмма" / "Export_facings.csv", sep=";", dtype={"STORENUMBER" : "str"})
facings.head()

,STORENUMBER,SECTIONID,STOCKCODE,XFACINGS,YFACINGS,ZFACINGS,MAX_CAPACITY,MIN_CAPACITY
0,10,20055,13880,3,1,5,15,6
1,10,20055,13881,3,1,5,15,6
2,10,20055,15794,1,1,7,7,2
3,10,20055,36571,2,1,6,12,4
4,10,20055,36571,2,1,6,12,4

In [11]:
stores = pd.read_excel(root_dir / "SPR_Магазины_Сеть_РД.xlsx", dtype={"Магазин" : "str"})
stores.head()

,Магазин,Сеть,Типоразмер,Куратор,Организация,Дата открытия,"Площадь общая, м2","Площадь ТЗ, м2",Район,Географическое положение,Формат,Ассортимент,Тип цен реализации,Режим работы,Телефон,Адрес,Номер группы
0,2,Сеть 1,NaN,Куратор 3,Фирма 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,Сеть 1,NaN,Куратор 3,Фирма 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,Сеть 1,NaN,Куратор 3,Фирма 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,Сеть 1,NaN,Куратор 2,Фирма 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,Сеть 1,NaN,Куратор 4,Фирма 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
nomenclature = pd.read_excel(root_dir / "SPR_Номенклатура_NEW.xlsx")
nomenclature.head()

,Номенклатура,Срок хранения товара,Код,Штрих-Код,Уровень2,Уровень3,Уровень4,Уровень5,KVI,ТПЦ,...,Номенклатура.Производитель,Номенклатура.Поставщик,Номенклатура.Бренд,Номенклатура.СТМ,Номенклатура.Эксклюзив,Номенклатура.Базовая единица измерения,Номенклатура.Поставщик.Код,Возвратный товар,СреднийВес,ОсновнаяЕдиницаИзмерения
0,Товар 1,0,1,NaN,04 Замороженная продукция,0403 Рыба и морепродукты замороженные,040301 Рыба и Филе рыбы зам,04030102 Рыба белая тушка зам,Нет,Нет,...,NaN,Тер-Тумасов В.Б. ИП,NaN,Нет,Нет,кг,ЦБ000464,NaN,NaN,кг
1,Товар 2,0,756,NaN,07 Непродовольственные товары,0705 Товары для уборки,"070501 Губки, тряпки, швабры",07050103 Губки для посуды,Нет,Нет,...,NaN,Бененсон А.Л. ИП,NaN,Нет,Нет,шт,ЦБ000463,NaN,NaN,шт
2,Товар 3,0,766,NaN,07 Непродовольственные товары,"0714 Товары для праздника, Сувениры",071405 Новогодний ассортимент,"07140503 Гирлянды, мишура",Нет,Нет,...,NaN,Бененсон А.Л. ИП,Vegas,Нет,Нет,шт,ЦБ000463,NaN,NaN,шт
3,Товар 4,0,773,NaN,07 Непродовольственные товары,"0714 Товары для праздника, Сувениры",071405 Новогодний ассортимент,"07140503 Гирлянды, мишура",Нет,Нет,...,NaN,Бененсон А.Л. ИП,Vegas,Нет,Нет,шт,ЦБ000463,NaN,NaN,шт
4,Товар 5,0,812,NaN,07 Непродовольственные товары,"0714 Товары для праздника, Сувениры",071405 Новогодний ассортимент,"07140503 Гирлянды, мишура",Нет,Нет,...,NaN,Бененсон А.Л. ИП,Vegas,Нет,Нет,шт,ЦБ000463,NaN,NaN,шт

In [13]:
sales = pd.read_csv(root_dir / "Продажи" / "SPR_Среднедневные_продажи.csv", sep=",", dtype={"Магазин" : "str"})
sales.head()

  Магазин  Код товара  Продажи, ед. изм.
0       2         756           1.191209
1       2         773           0.972093
2       2         906           1.145055
3       2         909           0.681319
4       2         945           0.426637

Переименование одинаковых колонок

In [14]:
col_vol = "Объём товара в закрывающемся магазине (V)"
col_maxcap = "Максимальная вместимость товара в магазине (M)"
col_item = "Код товара"
col_store = "Магазин"
col_status = "Ассортимент Статус"
col_remain = "Остаток товара в магазине (R)"
col_sales = "Продажи товара в магазине (S)"
col_measure = "Единица измерения"
col_left = "остаток_робот"

In [15]:
assortment = assortment.rename(columns={"№Магазина" : col_store, "Номер SKU" : col_item})
leftovers = leftovers.rename(columns={"номер магазина" : col_store, "код товара" : col_item})
facings = facings.rename(columns={"STORENUMBER" : col_store, "STOCKCODE" : col_item})
stores = stores.rename(columns={"Магазин" : col_store})
nomenclature = nomenclature.rename(columns={"Код" : col_item, "ОсновнаяЕдиницаИзмерения" : col_measure})
sales = sales.rename(columns={"Код товара" : col_item, "Магазин" : col_store, "Продажи, ед. изм." : col_sales})

In [16]:
leftovers[col_left] = leftovers[col_left].replace(r"\s+", "", regex=True)  # убрать пробелы в числах
leftovers[col_left] = leftovers[col_left].replace(",", ".", regex=True)  # т.к. по стандарту разделение через .
leftovers[col_left] = pd.to_numeric(leftovers[col_left])
leftovers[col_left] = leftovers[col_left].fillna(0)
leftovers.loc[leftovers[col_left] < 0, col_left] = 0  # если остаток отрицательный, то полагается, что товара нет на складе
leftovers.head()

  Магазин  Код товара остаток  остаток_робот
0      05      215673   4,000            4.0
1      75      215673   8,000            8.0
2     137      226249  24,000           24.0
3      39      226249  29,000           29.0
4      08      226249  30,000           30.0

## Предварительная работа с датасетами

Товары закрывающегося магазина

In [17]:
items = leftovers[leftovers[col_store] == closing_store]
items = items.rename(columns={col_left : col_vol})

Номенклатура и срок годности товаров в закрывающемся магазине

In [18]:
items = items.merge(nomenclature, left_on=col_item, right_on=col_item, how="left").filter(items=[col_item, "Уровень3", col_vol, "Срок хранения товара", col_measure])
items["Срок хранения товара"] = items["Срок хранения товара"].fillna(0)  # на случай, если срок годности не указан, ставим 0 и считаем непортящимся
items.head()

,Код товара,Уровень3,Объём товара в закрывающемся магазине (V),Срок хранения товара,Единица измерения
0,226249,0501 Консервация,10.0,0,шт
1,234761,0901 Сырье СП,3.0,0,кг
2,215959,"0101 Фрукты, Овощи, Зелень, Грибы",53.0,14,кг
3,237251,"0904 Тара, Упаковка и прочее",3.0,0,шт
4,217430,0705 Товары для уборки,12.0,0,шт

Фильтрация по сроку хранения товара. Если срок хранения товара равен 0, то товар считается непортящимся

In [19]:
if spoilage_threshold > 0:
    items = items[(items["Срок хранения товара"] == 0) | (items["Срок хранения товара"] >= spoilage_threshold)]
items.head()

,Код товара,Уровень3,Объём товара в закрывающемся магазине (V),Срок хранения товара,Единица измерения
0,226249,0501 Консервация,10.0,0,шт
1,234761,0901 Сырье СП,3.0,0,кг
3,237251,"0904 Тара, Упаковка и прочее",3.0,0,шт
4,217430,0705 Товары для уборки,12.0,0,шт
5,230261,0608 Табачные изделия,21.0,0,шт

Магазины, где распределяемые товары состоят в продаже

In [20]:
potential_stores = assortment[assortment[col_store] != closing_store]
items = items.merge(potential_stores, left_on=col_item, right_on=col_item).filter(items=[col_item, "Уровень3", col_store, col_status, col_vol, col_measure])
items = items[items[col_status] == "Введен"]
items.head()

,Код товара,Уровень3,Магазин,Ассортимент Статус,Объём товара в закрывающемся магазине (V),Единица измерения
0,226249,0501 Консервация,54,Введен,10.0,шт
1,226249,0501 Консервация,56,Введен,10.0,шт
2,226249,0501 Консервация,57,Введен,10.0,шт
3,226249,0501 Консервация,60,Введен,10.0,шт
4,226249,0501 Консервация,61,Введен,10.0,шт

Определяем куратора и организацию этих магазинов

In [21]:
items = items.merge(stores, left_on=col_store, right_on=col_store).filter(items=[col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_measure])
items.head()

,Код товара,Уровень3,Магазин,Куратор,Организация,Объём товара в закрывающемся магазине (V),Единица измерения
0,226249,0501 Консервация,54,Куратор 1,Фирма 1,10.0,шт
1,226249,0501 Консервация,56,Куратор 5,Фирма 1,10.0,шт
2,226249,0501 Консервация,57,Куратор 2,Фирма 1,10.0,шт
3,226249,0501 Консервация,60,Куратор 2,Фирма 1,10.0,шт
4,226249,0501 Консервация,61,Куратор 2,Фирма 1,10.0,шт

Куратор и организация закрывающегося магазина

In [22]:
closing_curator, closing_organization = stores[stores[col_store] == closing_store].filter(items=["Куратор", "Организация"]).iloc[0].values
print("Куратор:", closing_curator)
print("Организация:", closing_organization)

Куратор: Куратор 3
Организация: Фирма 4

Теперь добавляем среднедневные продажи товаров по магазинам

In [23]:
items = items.merge(sales, left_on=[col_item, col_store], right_on=[col_item, col_store]).filter(items=[col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_sales, col_measure])
items.head()

,Код товара,Уровень3,Магазин,Куратор,Организация,Объём товара в закрывающемся магазине (V),Продажи товара в магазине (S),Единица измерения
0,226249,0501 Консервация,54,Куратор 1,Фирма 1,10.0,1.379157,шт
1,226249,0501 Консервация,56,Куратор 5,Фирма 1,10.0,0.943567,шт
2,226249,0501 Консервация,57,Куратор 2,Фирма 1,10.0,0.857143,шт
3,226249,0501 Консервация,60,Куратор 2,Фирма 1,10.0,0.406742,шт
4,226249,0501 Консервация,61,Куратор 2,Фирма 1,10.0,0.713024,шт

Найдём размерность полок в магазинах. Очевидно, если дублируется магазин и код товара, то полок несколько и их нужно сложить

In [24]:
items = items.merge(facings, left_on=[col_item, col_store], right_on=[col_item, col_store]).filter(items=[col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_sales, col_measure, "XFACINGS", "YFACINGS", "ZFACINGS"])
items[["XFACINGS", "YFACINGS", "ZFACINGS"]] = items[["XFACINGS", "YFACINGS", "ZFACINGS"]].replace(0, 1)  # 0 быть не может физически, как минимум 1 предмет влезет
items[col_maxcap] = items["XFACINGS"] * items["YFACINGS"] * items["ZFACINGS"]  # получаем максимальную вместимость
items = items.drop(columns=["XFACINGS", "YFACINGS", "ZFACINGS"])

# Сумма дублей
duplicates = items[items.duplicated(subset=[col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_sales, col_measure], keep=False)]
unduplicated = duplicates.groupby([col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_sales, col_measure], as_index=False)[col_maxcap].sum()

# Удаляем дубликаты из исходной
items = items.drop_duplicates(subset=[col_item, col_store], keep=False)

# Вместо них добавим уже просуммированные значения
items = pd.concat([items, unduplicated])
items.head()

,Код товара,Уровень3,Магазин,Куратор,Организация,Объём товара в закрывающемся магазине (V),Продажи товара в магазине (S),Единица измерения,Максимальная вместимость товара в магазине (M)
0,226249,0501 Консервация,54,Куратор 1,Фирма 1,10.0,1.379157,шт,8
1,226249,0501 Консервация,56,Куратор 5,Фирма 1,10.0,0.943567,шт,8
2,226249,0501 Консервация,57,Куратор 2,Фирма 1,10.0,0.857143,шт,8
3,226249,0501 Консервация,60,Куратор 2,Фирма 1,10.0,0.406742,шт,8
4,226249,0501 Консервация,61,Куратор 2,Фирма 1,10.0,0.713024,шт,8

Остатки товара в каждом магазине

In [25]:
items = items.merge(leftovers, left_on=[col_item, col_store], right_on=[col_item, col_store]).filter(items=[col_item, "Уровень3", col_store, "Куратор", "Организация", col_vol, col_sales, col_maxcap, col_left, col_measure])
items = items.rename(columns={col_left : col_remain})
items.head()

,Код товара,Уровень3,Магазин,Куратор,Организация,Объём товара в закрывающемся магазине (V),Продажи товара в магазине (S),Максимальная вместимость товара в магазине (M),Остаток товара в магазине (R),Единица измерения
0,226249,0501 Консервация,54,Куратор 1,Фирма 1,10.0,1.379157,8,16.0,шт
1,226249,0501 Консервация,56,Куратор 5,Фирма 1,10.0,0.943567,8,22.0,шт
2,226249,0501 Консервация,57,Куратор 2,Фирма 1,10.0,0.857143,8,19.0,шт
3,226249,0501 Консервация,60,Куратор 2,Фирма 1,10.0,0.406742,8,28.0,шт
4,226249,0501 Консервация,61,Куратор 2,Фирма 1,10.0,0.713024,8,22.0,шт

Смотрим на основную единицу измерения и если это кг или м, то делим их на количество кг или м в одной штуке

In [26]:
items.loc[items[col_measure] == "кг", [col_vol, col_maxcap, col_remain]] /= kilos_in_one_piece
items.loc[items[col_measure] == "м", [col_vol, col_maxcap, col_remain]] /= meters_in_one_piece

Нецелые данные о количестве товара округляем

In [27]:
items = items.round({col_vol : 0, col_maxcap : 0, col_remain : 0})

Делим на алкогольную и безалкогольную продукцию

In [28]:
alcohol_items = None

if separate_alcohol:
    alcohol_items = items[
        (items["Уровень3"] == "0601 Напитки безалкогольные") | 
        (items["Уровень3"] == "0602 Водка и Настойки") |
        (items["Уровень3"] == "0603 Крепкие спиртные напитки") |
        (items["Уровень3"] == "0604 Игристые вина") |
        (items["Уровень3"] == "0605 Вермут") |
        (items["Уровень3"] == "0606 Вино") |
        (items["Уровень3"] == "0607 Слабоалкогольные напитки")]

    items = items[
        (items["Уровень3"] != "0601 Напитки безалкогольные") & 
        (items["Уровень3"] != "0602 Водка и Настойки") &
        (items["Уровень3"] != "0603 Крепкие спиртные напитки") &
        (items["Уровень3"] != "0604 Игристые вина") &
        (items["Уровень3"] != "0605 Вермут") &
        (items["Уровень3"] != "0606 Вино") &
        (items["Уровень3"] != "0607 Слабоалкогольные напитки")]

Если это требуется, оставляем только магазины с тем же куратором или организацией

In [29]:
if same_curator and same_organization:
    items = items[(items["Куратор"] == closing_curator) | (items["Организация"] == closing_organization)]

elif same_curator:
    items = items[items["Куратор"] == closing_curator]

elif same_organization:
    items = items[items["Организация"] == closing_organization]

items = items.filter(items=[col_item, col_store, col_vol, col_sales, col_maxcap, col_remain])  # оставляем только нужные колонки

Для алкогольной продукции всегда оставляем магазины только в пределах этой же организации

In [30]:
if alcohol_items is not None:
    alcohol_items = alcohol_items[alcohol_items["Организация"] == closing_organization]
    alcohol_items = alcohol_items.filter(items=[col_item, col_store, col_vol, col_sales, col_maxcap, col_remain])  # оставляем только нужные колонки

Итог

In [31]:
items

,Код товара,Магазин,Объём товара в закрывающемся магазине (V),Продажи товара в магазине (S),Максимальная вместимость товара в магазине (M),Остаток товара в магазине (R)
0,226249,54,10.0,1.379157,8,16.0
1,226249,56,10.0,0.943567,8,22.0
2,226249,57,10.0,0.857143,8,19.0
3,226249,60,10.0,0.406742,8,28.0
4,226249,61,10.0,0.713024,8,22.0
...,...,...,...,...,...,...
413684,239388,95,26.0,1.500000,25,20.0
413685,239397,38,12.0,1.116279,24,21.0
413686,239398,38,13.0,2.023256,24,45.0
413687,239515,38,42.0,1.796296,30,35.0
413688,239516,38,42.0,1.740741,24,28.0

In [32]:
alcohol_items

## Выгрузка отфильтрованых датасетов

In [33]:
def output_csv(df, filename, with_index=False):
    df_dirpath = Path(r"./filtered_datasets")
    df_dirpath.mkdir(parents=True, exist_ok=True)

    df_filepath = df_dirpath / filename

    with df_filepath.open("w") as f:
        df.to_csv(f, sep=";", lineterminator="\n", index=with_index)

In [34]:
output_csv(items, "items_closing_store.csv")

In [35]:
if alcohol_items is not None:
    output_csv(alcoholitems, "alcohol_items_closing_store.csv")